// Generated by gencpp from file swarm_controller/velocity_msg.msg
// DO NOT EDIT!


#ifndef SWARM_CONTROLLER_MESSAGE_VELOCITY_MSG_H
#define SWARM_CONTROLLER_MESSAGE_VELOCITY_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_controller
{
template <class ContainerAllocator>
struct velocity_msg_
{
  typedef velocity_msg_<ContainerAllocator> Type;

  velocity_msg_()
    : velocity(0.0)
    , slot_id(0)  {
    }
  velocity_msg_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , slot_id(0)  {
  (void)_alloc;
    }



   typedef float _velocity_type;
  _velocity_type velocity;

   typedef int32_t _slot_id_type;
  _slot_id_type slot_id;





  typedef boost::shared_ptr< ::swarm_controller::velocity_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_controller::velocity_msg_<ContainerAllocator> const> ConstPtr;

}; // struct velocity_msg_

typedef ::swarm_controller::velocity_msg_<std::allocator<void> > velocity_msg;

typedef boost::shared_ptr< ::swarm_controller::velocity_msg > velocity_msgPtr;
typedef boost::shared_ptr< ::swarm_controller::velocity_msg const> velocity_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_controller::velocity_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_controller::velocity_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_controller::velocity_msg_<ContainerAllocator1> & lhs, const ::swarm_controller::velocity_msg_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity &&
    lhs.slot_id == rhs.slot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_controller::velocity_msg_<ContainerAllocator1> & lhs, const ::swarm_controller::velocity_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::swarm_controller::velocity_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_controller::velocity_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_controller::velocity_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_controller::velocity_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_controller::velocity_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_controller::velocity_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_controller::velocity_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd5e463c1daf6ea79e9b4940515d2e74";
  }

  static const char* value(const ::swarm_controller::velocity_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd5e463c1daf6ea7ULL;
  static const uint64_t static_value2 = 0x9e9b4940515d2e74ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_controller::velocity_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_controller/velocity_msg";
  }

  static const char* value(const ::swarm_controller::velocity_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_controller::velocity_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocity\n"
"int32 slot_id\n"
;
  }

  static const char* value(const ::swarm_controller::velocity_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_controller::velocity_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.slot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct velocity_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_controller::velocity_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_controller::velocity_msg_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "slot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.slot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_CONTROLLER_MESSAGE_VELOCITY_MSG_H
