
vehicle_names: ["duckie3", "duckie2"]

velocity_sender_server_socket_number_0: 5021
velocity_sender_server_socket_number_1: 5023

slot_controller_server_socket_number: 5001

lane_width: 0.2
num_lanes: 2
road_length: 3.5
lane_velocities: [0.025, 0.05]
num_slots_per_lane: 3
slot_length: 0.1
slot_gap: 0.1
frequency: 1